import { Footer } from "@/components/footer";
import type { Metadata } from "next";
import { inika, irish } from "./fonts";
import "./globals.css";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Glimbi Tales",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{
          background: "#1E1A3F",
          color: "#fff",
        }}
        className={`${irish.className} ${inika.className}`}
      >
        <Providers>
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
